package com.spring.ledzer.model;
// Generated Jul 11, 2018 1:39:54 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * BusinessDetails generated by hbm2java
 */
@Entity
@Table(name = "business_detail")
public class BusinessDetail extends DateAudit<Integer> implements java.io.Serializable {

	private Long id;
	private String name;
	private String owner;
	private String address;
	private String city;
	private State state;
	private String phone;
	private String email;
	private String website;
	private String pan;
	private String tin;
	private String gstin;
	private String logo;

	public BusinessDetail(String name, String owner, String address, String city, State state, String phone,
			String email, String website, String pan, String tin, String gstin, String logo) {
		super();
		this.name = name;
		this.owner = owner;
		this.address = address;
		this.city = city;
		this.state = state;
		this.phone = phone;
		this.email = email;
		this.website = website;
		this.pan = pan;
		this.tin = tin;
		this.gstin = gstin;
		this.logo = logo;
	}


	public BusinessDetail() {
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "owner", length = 200)
	public String getOwner() {
		return owner;
	}


	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@OneToOne
    @JoinColumn(name="state_id")
	public State getState() {
		return state;
	}


	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "phone", length = 10)
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "website", length = 20)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}
	
	@Column(name = "pan", length = 20)
	public String getPan() {
		return pan;
	}


	public void setPan(String pan) {
		this.pan = pan;
	}

	@Column(name = "tin", length = 20)
	public String getTin() {
		return tin;
	}


	public void setTin(String tin) {
		this.tin = tin;
	}

	@Column(name = "gstin", length = 20)
	public String getGstin() {
		return this.gstin;
	}

	public void setGstin(String gstin) {
		this.gstin = gstin;
	}

	@Column(name = "logo", length = 30, nullable=true)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}


}
