package com.spring.ledzer.model;

// Generated Dec 16, 2018 1:43:16 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.spring.ledzer.converter.GenderConverter;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer")
public class Customer extends DateAudit<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	private Long id;
	private State state;
	private String name;
	@Convert(converter = GenderConverter.class)
	private Gender gender;
	private String address;
	private String shipAdd;
	private String city;
	private String pin;
	private String mobno;
	private String email;
	private String gstin;
	private String tin;
	private String vat;
	private String pan;
	private String stn;
	private BigDecimal outBal;
	private BigDecimal totalAmtPaid;
	
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	private Set<InvoicePayments> invoicePayments = new HashSet<InvoicePayments>(0);
	private Set<CustomerPayment> customerPayments = new HashSet<CustomerPayment>(0);
	
	public Customer() {
		
		 super();
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "state_id")
	@JsonIgnore
	public State getState() {
		return this.state;
	}
	
	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Gender getGender() {
		return gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "ship_add", length = 500)
	public String getShipAdd() {
		return this.shipAdd;
	}

	public void setShipAdd(String shipAdd) {
		this.shipAdd = shipAdd;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "pin", length = 6)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "mobno", length = 13)
	public String getMobno() {
		return this.mobno;
	}

	public void setMobno(String mobno) {
		this.mobno = mobno;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "gstin", length = 20)
	public String getGstin() {
		return this.gstin;
	}

	public void setGstin(String gstin) {
		this.gstin = gstin;
	}

	@Column(name = "tin", length = 15)
	public String getTin() {
		return this.tin;
	}

	public void setTin(String tin) {
		this.tin = tin;
	}

	@Column(name = "vat", length = 10)
	public String getVat() {
		return this.vat;
	}

	public void setVat(String vat) {
		this.vat = vat;
	}

	@Column(name = "pan", length = 10)
	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	@Column(name = "stn", length = 15)
	public String getStn() {
		return this.stn;
	}

	public void setStn(String stn) {
		this.stn = stn;
	}

	@Column(name = "out_bal", precision = 15)
	public BigDecimal getOutBal() {
		return this.outBal;
	}

	public void setOutBal(BigDecimal outBal) {
		this.outBal = outBal;
	}

	@Column(name = "total_amt_paid", precision = 15)
	public BigDecimal getTotalAmtPaid() {
		return this.totalAmtPaid;
	}

	public void setTotalAmtPaid(BigDecimal totalAmtPaid) {
		this.totalAmtPaid = totalAmtPaid;
	}

	@OneToMany(cascade=CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Invoice> getInvoices() {
		return invoices;
	}
	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<InvoicePayments> getInvoicePayments() {
		return invoicePayments;
	}
	public void setInvoicePayments(Set<InvoicePayments> invoicePayments) {
		this.invoicePayments = invoicePayments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerPayment> getCustomerPayments() {
		return customerPayments;
	}

	public void setCustomerPayments(Set<CustomerPayment> customerPayments) {
		this.customerPayments = customerPayments;
	}

}
