package com.spring.ledzer.model;
// Generated Dec 16, 2018 1:43:16 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * InvoicePaymentHistory generated by hbm2java
 */
@Entity
@Table(name = "invoice_payments")
public class InvoicePayments extends DateAudit<Long> implements java.io.Serializable {

	private Long id;
	private Long paymentNumber;
	private String paymentVoucher;
	private BigDecimal invTotalAmt;
	private BigDecimal amountPaid;
	private BigDecimal amountDue;
	private Date paymentDate;
	private Account account;
	private PaymentMode paymentMode;
	private String chequeNo;
	private String bankName;
	
	private Customer customer;
	private Invoice invoice;
	
	public InvoicePayments() {
		super();
	}


	public InvoicePayments(Long paymentNumber, String paymentVoucher, BigDecimal invTotalAmt, BigDecimal amountPaid,
			BigDecimal amountDue, Date paymentDate, Account account, PaymentMode paymentMode, String chequeNo,
			String bankName, Invoice invoice, Customer customer) {
		super();
		this.paymentNumber = paymentNumber;
		this.paymentVoucher = paymentVoucher;
		this.invTotalAmt = invTotalAmt;
		this.amountPaid = amountPaid;
		this.amountDue = amountDue;
		this.paymentDate = paymentDate;
		this.account = account;
		this.paymentMode = paymentMode;
		this.chequeNo = chequeNo;
		this.bankName = bankName;
		this.customer = customer;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name = "payment_number")
    public Long getPaymentNumber() {
		return paymentNumber;
	}

	public void setPaymentNumber(Long paymentNumber) {
		this.paymentNumber = paymentNumber;
	}

	@Column(name = "payment_voucher", length = 30)
	public String getPaymentVoucher() {
		return paymentVoucher;
	}

	public void setPaymentVoucher(String paymentVoucher) {
		this.paymentVoucher = paymentVoucher;
	}

    @Column(name = "amount_paid", precision = 10)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "amount_due", precision = 15)
	public BigDecimal getAmountDue() {
		return this.amountDue;
	}

	public void setAmountDue(BigDecimal amountDue) {
		this.amountDue = amountDue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "account_id", nullable = false)
	@JsonManagedReference
	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "payment_mode_id", nullable = false)
	@JsonManagedReference
	public PaymentMode getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(PaymentMode paymentMode) {
		this.paymentMode = paymentMode;
	}
	@Column(name = "cheque_no", length = 20)
	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	@Column(name = "bank_name", length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	@JsonIgnore
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "inv_total_amt", precision = 10)
	public BigDecimal getInvTotalAmt() {
		return this.invTotalAmt;
	}

	public void setInvTotalAmt(BigDecimal invTotalAmt) {
		this.invTotalAmt = invTotalAmt;
	}

	@OneToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "invoice_id", nullable = false)
	public Invoice getInvoice() {
		return invoice;
	}


	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

}
